# Generated by Django 4.1.9 on 2024-01-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_sala_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='status',
            new_name='ativo',
        ),
    ]
