# Generated by Django 4.1.9 on 2024-01-16 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_rename_status_sala_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='ativo',
            new_name='ativa',
        ),
        migrations.AddField(
            model_name='sala',
            name='hora_fim',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='sala',
            name='hora_inicio',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='sala',
            name='minutos_fim',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='sala',
            name='minutos_inicio',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
    ]
