# Generated by Django 4.1.9 on 2024-01-16 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0006_horariodisponivel'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horario_disponivel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='salas.horariodisponivel'),
        ),
    ]
